/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define if the X Window System is missing or not being used.  */
/* #undef X_DISPLAY_MISSING */

/* Define if you have the select function.  */
#define HAVE_SELECT 1

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the X11 library (-lX11).  */
#define HAVE_LIBX11 1

/* Define if you have the Xext library (-lXext).  */
#define HAVE_LIBXEXT 1

/* Define if you have the Xpm library (-lXpm).  */
#define HAVE_LIBXPM 1

/* Name of package */
#define PACKAGE "epiwm"

/* Version number of package */
#define VERSION "0.5.6"

/* Define to not use libxpm for logoepiwm */
/* #undef NOXPM */

/* Define to use Imlib for image rendering */
#define IMLIB 1

/* Define configuration files path */
#define CONFIG_PATH "/etc/X11/epiwm"

